### ISSUE TITLE
ERROR: Gem bundler is not installed, run `gem install bundler` first.

### ISSUE THREAD

**Issue by kule** [rvm/rvm#1043]
I keep having this issue even with a fresh install is it a known problem?

I can get around it by copying/symlinking to the bundle file as per this answer:

http://stackoverflow.com/a/9070597/233004

All the rubies (1.8.7, 1.9.2, 1.9.3) seem to compile & install correctly but they all come up with this error.

Is this just because of running with the latest XCode (4.3.3)?  I'm running on 10.7.4.

Here's my PATH:

/Users/luke/.rvm/gems/ruby-1.9.3-p194@gem-portal/bin:/Users/luke/.rvm/gems/ruby-1.9.3-p194@global/bin:/Users/luke/.rvm/rubies/ruby-1.9.3-p194/bin:/Users/luke/.rvm/bin:/Users/luke/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin

**Comment by parag90** [comment]
Hey @mpapis 
After reading all the comments above I am thanking you in advance for the solution I am asking.

I am facing same issue. When everever I am running test from my rubymine it says bundler missing 
Here are my env details

DELC02PQ5TNG8WN:cucumber pajain$ echo $GEM_HOME
/Users/pajain/.rvm/gems/ruby-2.2.6

DELC02PQ5TNG8WN:cucumber pajain$ echo $GEM_PATH
/Users/pajain/.rvm/gems/ruby-2.2.6:/Users/pajain/.rvm/gems/ruby-2.2.6@global

DELC02PQ5TNG8WN:cucumber pajain$ echo $PATH
/Users/pajain/.rvm/gems/ruby-2.2.6/bin:/Users/pajain/.rvm/gems/ruby-2.2.6@global/bin:/Users/pajain/.rvm/rubies/ruby-2.2.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pajain/apache-maven-3.3.3/bin:/Users/pajain/office/ADB:/Users/pajain/Downloads:/Users/pajain/.rvm/bin

DELC02PQ5TNG8WN:cucumber pajain$ which bundle
/Users/pajain/.rvm/gems/ruby-2.2.6/bin/bundle

DELC02PQ5TNG8WN:cucumber pajain$ gem env 
Failed to load /Users/pajain/.gemrc because it doesn't contain valid YAML hash
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.8
  - RUBY VERSION: 2.2.6 (2016-11-15 patchlevel 396) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/pajain/.rvm/gems/ruby-2.2.6
  - USER INSTALLATION DIRECTORY: /Users/pajain/.gem/ruby/2.2.0
  - RUBY EXECUTABLE: /Users/pajain/.rvm/rubies/ruby-2.2.6/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/pajain/.rvm/gems/ruby-2.2.6/bin
  - SPEC CACHE DIRECTORY: /Users/pajain/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/pajain/.rvm/rubies/ruby-2.2.6/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/pajain/.rvm/gems/ruby-2.2.6
     - /Users/pajain/.rvm/gems/ruby-2.2.6@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/pajain/.rvm/gems/ruby-2.2.6/bin
     - /Users/pajain/.rvm/gems/ruby-2.2.6@global/bin
     - /Users/pajain/.rvm/rubies/ruby-2.2.6/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/pajain/apache-maven-3.3.3/bin
     - /Users/pajain/office/ADB
     - /Users/pajain/Downloads
     - /Users/pajain/.rvm/bin

**Comment by mpapis** [comment]
@parag90 make sure rubymine is configured to use ruby-2.2.6 without a gemset - if this does not help - open a new ticket ... or ask on stackoverflow

**Comment by parag90** [comment]
@mpapis created issue https://github.com/rvm/rvm/issues/3864
