### ISSUE TITLE
curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by scaryguy** [rvm/rvm#2208]
Hi there...

Ubuntu 13.04 here.

I'm trying to install RVM using your script but I get this error:

``` console
scaryguy@scary:~$ \curl -L https://get.rvm.io | bash -s stable  
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0     11      0  0:00:16  0:00:16 --:--:--   176
  0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

I googled a lot. I even found your support page about it but whenever I try to use `sudo apt-get install ca-certificates` , it says that's already installed.

I don't want to use `-k` options since I heard that this issue can affect connection between rubygems.org too.

**Comment by salsa-dev** [comment]
To whom it may concern (POSSIBLE SOLUTION):
I'm on new installation of Debian (Jessie) trying to install rvm with curl and hit the error described here. Tried every possible solution found on web but nothing was of any help. It is already late and I check time with "date" to go sleep. Here we are!!!! The date is 13 years behind!!!!!!!! Syncing with ntp resolved an issue. So, dear admin, please check the time on your server!

**Comment by petrbela** [comment]
I was getting a similar error with openssl 1.0.2k. After upgrading to 1.0.2n, the problem disappeared.

**Comment by BradleyGyemi-Qlik** [comment]
Certificate seems to have expired again:

In Dockerfile:

RUN command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import - \
	&& command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import - \
	&& curl -sSL https://get.rvm.io | bash -s stable \
	
returns:

gpg: key 3804BB82D39DC0E3: 47 signatures not checked due to missing keys
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 3804BB82D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no ultimately trusted keys found
gpg: key 105BD0E739499BDB: public key "Piotr Kuczynski <piotr.kuczynski@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
curl: (60) SSL certificate problem: certificate has expired
