### ISSUE TITLE
RVM creates unneccessary Shell Config Files

### ISSUE THREAD

**Issue by yooden** [rvm/rvm#2480]
During install, rvm 1.25.8 creates config files for various shells I don't intend to use, eg. ~/.profile, ~/.bashrc. Please do not write to config files this scattershotty, at least not as a default.

**Comment by aschultzq** [comment]
The --ignore-dotfiles option should be the default, or at least more prominent on the installation page.

After installing rvm my shell's behavior changed for the worse. If I would have known it was going to be modifying my environment I would have chosen this option, but it was buried in a wall of text.

Now I'm wasting cycles looking to get my environment back.

**Comment by phillipp** [comment]
I think this discussion is getting out of hand. The problem here is expectation of the installation process. I have to agree with @mpapis that the scope of RVM is to have like a one-click-installer for setting up ruby. Adding dotfiles for various shells is part of that imho and should be default and not optional.

I can agree on that documentation could (as always) be better. So I would recommend you update the docs by opening a pull request to make it more clear what the installation will do. But looking at the docs I think it's pretty clear that the option exist. It's pretty much about "what do you expect from the installation" and everyone may think different about that. But changing the behaviour is **not** what is to be expected.

Maybe you can be more specific how the installation exactly the installation changed your env to the worse, because there may be a legit issue if your shell breaks when installing RVM. That should be addressed as a seperate issue to keep it seperated from this issue.
