### ISSUE TITLE
When installing jruby from prepared package, importing gemset is slow

### ISSUE THREAD

**Issue by grk** [rvm/rvm#2728]
Using latest rvm master (1.15.21)

I installed jruby on one server, ran `rvm prepare` to make it accessible over http, then installed on another with `rvm install` with `rvm_remote_server_url` set to my url.

All mri rubies install fast, but on jruby the importing gemset step takes much logner.

**Comment by sheldonh** [comment]
I think the reason the gemset import is so slow on jruby is that gemset import runs one gem command per gem imported. I conclude this from code inspection only. Jruby startup time is so bad that this takes over 6 minutes in my Travis CI builds.

The solution is probably to modify gemset_import (or at least gemset_import_list) so that a single gem command is used to install multiple gems.

Please consider leaving the bug open, so that other JRuby users will find it easily (and maybe even contribute a fix!) :-)

**Comment by mpapis** [comment]
@sheldonh  should be better on master, in my local tests the installation time dropped from 3:30 to 2:15
