### ISSUE TITLE
Heroku Toolbelt broke the PATH Variable, and rvm keeps telling me to update PATH

### ISSUE THREAD

**Issue by izzyleung** [rvm/rvm#3038]
As `/usr/local/heroku/bin` is now in the first place in my PATH variable, rvm keeps complaining that the PATH is broken.

How can I move heroku's path variable after rvm?

Thanks in advance.

**Comment by vjwilson** [comment]
I just had to set up a new Mac for development, and I was getting a similar warning.

It seems both rvm and heroku toolbelt use `~/.bashrc`, instead of `~/.bash_profile` to add themselves to PATH:

```sh
### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
```

I just changed that first export statement to:

```sh
export PATH="$PATH:/usr/local/heroku/bin"
```

and that got rid of the rvm warning without breaking heroku tools.

**Comment by johnivanoff** [comment]
I moved my RVM statement to to top to git rid of the warning
