### ISSUE TITLE
Cannot create wrappers

### ISSUE THREAD

**Issue by ginjo** [rvm/rvm#3055]
Trying to create wrappers for 1.8.7-head, for passenger, but it's not happening.

```
user@host:~/$ rvm wrapper current passenger
Regenerating ruby-1.8.7-head wrappers..............
Could not find file 'ruby' nor '/usr/local/rvm/wrappers/ruby-1.8.7-head/ruby'.
Could not find file 'gem' nor '/usr/local/rvm/wrappers/ruby-1.8.7-head/gem'.
Could not find file 'irb' nor '/usr/local/rvm/wrappers/ruby-1.8.7-head/irb'.
Could not find file 'ri' nor '/usr/local/rvm/wrappers/ruby-1.8.7-head/ri'.
Could not find file 'rdoc' nor '/usr/local/rvm/wrappers/ruby-1.8.7-head/rdoc'.
Could not find file 'rake' nor '/usr/local/rvm/wrappers/ruby-1.8.7-head/rake'.
Could not find file 'erb' nor '/usr/local/rvm/wrappers/ruby-1.8.7-head/erb'.
Could not find file 'testrb' nor '/usr/local/rvm/wrappers/ruby-1.8.7-head/testrb'.
```

And I get this for 'rvm repair wrappers'  https://gist.github.com/ginjo/60d087ee823dc73c15f4

My original rvm & ruby installs went perfectly, without any errors, or so I thought. Rvm was installed as multi-user, from non-privileged account, using `bash -s stable --ruby` on Debian Jessie. The default 2.1.3 ruby that was installed works great, and does have working wrappers.

**Comment by Michael-Fletcher** [comment]
rvm doesn't install ruby in a normal way it throws it in /usr/share/rvm/rubies/ruby-<version>/bin/ruby instead of a directory such as /usr/bin meaning that the OS will inherently ignore its install when a command 'ruby' or anything else that was installed with rvm was used.  Due to it not being in the system path. 

I'm having the same issue with pump and pumactl.  If I install puma it also installs the wrong version of Ruby along side...  This sin't difficult to fix but the developers of rvm need to learn how make an installer run in a normal way e.g. 'apt install ruby<version>', 'yum install ruby<version>'.  Problems like this shouldn't be difficult. 
  
GemWrappers: Can not wrap missing file: puma
GemWrappers: Can not wrap missing file: pumactl
GemWrappers: Can not wrap missing file: puma
GemWrappers: Can not wrap missing file: pumactl

Instead of using 'bundle exec <command>'  you will need to manually locate the problem files and make a symbolic link (shortcut) to one of the system path locations such as /usr/bin or add an additional entry.  If your entry comes after another in the path with the same name, it will choose the first. 

RVM = NVG - Not Very Good.  Especially if you're like me and using a Ubuntu Docker image.
