### ISSUE TITLE
binary installed ruby 2.1.2 has incorrect darwin version on yosemite

### ISSUE THREAD

**Issue by nevinera** [rvm/rvm#3148]
I installed ruby-2.1.2 on a yosemite macbook air, and rvm fetched it from https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/ruby-2.1.2.tar.bz2

From `irb` afterwards though, `Gem::Platform.local.to_s` returns "x86_64-darwin-13".
The same operation in the binary-installed 2.1.1 produces `x86_64-darwin-12`, and from 2.1.4 we get `x86_64-darwin-14`.

From looking at the source directories on fastly.net, I notice that the different osx versions appear to be symlinks to the same directory, which is presumably the source of the problem.

This is a problem for people that distribute binary versions of their gem compiled for specific architectures - if I use `--disable-binary` when installing ruby-2.1.1, then compile my binary gem, and try to use it on a computer that did a binary install of ruby-2.1.1, it doesn't recognize that there's a usable version of the gem available.

I'm working around for now by just compiling on all three binary rubies so I can release darwin-12, darwin-13, and darwin-14 versions.

**Comment by shartep-elephant** [comment]
this help me:
- download ruby-2.1.1 from ftp://ftp.ruby-lang.org/pub/ruby/2.1/ruby-2.1.1.tar.gz
- unpack it
- in console go to dir ruby-2.1.1
- ./configure --prefix=/Users/devy/.rvm/rubies/ruby-2.1.1     #where devy is my username
- make
- sudo make install
- go to project directory and check ruby version, type ruby -v
- see: ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin14.0]
change source for Gems (because ./configure --with-openssl-dir=/usr/local/Cellar/openssl don't work for me):
- gem source -r https://rubygems.org/ 
- gem source -a http://rubygems.org/
