### ISSUE TITLE
Mention in PATH warnings about ability to silence them

### ISSUE THREAD

**Issue by mcandre** [rvm/rvm#3336]
As a power user, I want `rvm_silence_path_mismatch_check_flag=1` to be the default so that rvm plays more nicely with other PATH-noting systems such as Homebrew.

**Comment by havenwood** [comment]
A nice way to adjust your PATH to Homebrew's liking is to edit the order in `/etc/paths`.

**Comment by robolson** [comment]
As a power user, what is stopping you from adding `rvm_silence_path_mismatch_check_flag=1` to your `~/.rvmrc`?

**Comment by charginghawk** [comment]
@robolson About 30 minutes of Googling to figure out why it's throwing this error in the first place (and finding out that it's throwing it for no reason - nvm inserts itself first in the PATH, there isn't any conflict). Power user != omniscient.

**Comment by pkuczynski** [comment]
@charginghawk if you elaborate a little bit on the issue I could fix it. So far I do not understand what was @mcandre problem?

**Comment by charginghawk** [comment]
In my case, the issue is that rvm displays the path mismatch error, "Warning! PATH is not properly set up...", because nvm has inserted itself into the path before rvm.

See: https://github.com/creationix/nvm/issues/306

Since nvm and rvm don't actually conflict, this warning is a false flag. While it's possible to disable it, I agree that it should be disabled by default.

Maybe a better solution would be to make the warning smarter, by having it check if there's specifically ruby binaries earlier in the path (so that nvm doesn't trigger it). Or rvm might do a better job inserting itself first in the path, so that it predates nvm.

**Comment by pkuczynski** [comment]
RVM have no intention to force changes to user settings. It's just a warning, as some other tools might conflict with RVM. It would be hard for RVM to know which other paths might be conflicting as we can't always say what's in the path. @mpapis what you think?

We could improve the warning and mention about the `rvm_silence_path_mismatch_check_flag`. We should also add it to the documentation...

**Comment by mpapis** [comment]
@pkuczynski is right, there might be other paths and tools on your `PATH` that would conflict, not just `ruby`. The simplest example is `bundler` - you have a gemset with it and set it to `PATH` but do not set `GEM_PATH` - then it will not work to check if there is other `ruby` before RVM's `ruby`, and it will still cause problems. The warning is there to raise awareness, if you are sure all is good - the warning can be disabled.

**Comment by mpapis** [comment]
as for making it default - why not set it in your shell configuration file?

**Comment by binarykitchen** [comment]
possible to silence this via `rvm` command instead of an additional dotfile?
