### ISSUE TITLE
Make errors installing ruby 2.1.2 in cygwin

### ISSUE THREAD

**Issue by andreassudihardjo** [rvm/rvm#3426]
I'm trying to install ruby version 2.1.2 in cygwin on windows 8.1 but I seem to be encountering this problem:

Error running '__rvm_make -j4',
showing last 15 lines of /home/Andreas/.rvm/log/1432236208_ruby-2.1.2/make.log
make[2]: *** [printf.o] Error 1
make[2]: Leaving directory '/home/Andreas/.rvm/src/ruby-2.1.2/ext/-test-/printf'
exts.mk:109: recipe for target 'ext/-test-/printf/all' failed
make[1]: *** [ext/-test-/printf/all] Error 2
make[1]: *** Waiting for unfinished jobs....
installing default postponed_job libraries
installing default path_to_class libraries
linking shared-object -test-/path_to_class/path_to_class.so
make[2]: Leaving directory '/home/Andreas/.rvm/src/ruby-2.1.2/ext/-test-/path_to_class'
linking shared-object -test-/postponed_job.so
make[2]: Leaving directory '/home/Andreas/.rvm/src/ruby-2.1.2/ext/-test-/postponed_job'
make[1]: Leaving directory '/home/Andreas/.rvm/src/ruby-2.1.2'
uncommon.mk:180: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.

**Comment by samsoft00** [comment]
@andreassudihardjo is like we're having the same challenge? here is my logged issue? https://github.com/rvm/rvm/issues/3430

So, have you been able to resolve it?

**Comment by Nekromancer** [comment]
Same issue for version 2.2.2 here

**Comment by thomasmacneil** [comment]
I had the same problem with 2.1.4 and resolved as such.  I used the following three point of reference:

https://bugs.ruby-lang.org/issues/11065
http://sourceforge.net/p/cygwin-ports/ruby/ci/master/tree/2.2.2-cygwin-compile.patch#l4
https://rvm.io/rubies/patching

So, nutshell: there's a bug in the ruby source code that doesn't play nice with Cygwin.  But RVM has a patch mechanism for when you're compiling.  So, make a patch and have RVM use that when it installs it.  Here's my patch file:

--- /ext/-test-/printf/printf.c 2014-06-29 10:17:20.000000000 -0700
+++ /ext/-test-/printf/printf.c 2015-07-08 16:58:15.882479100 -0700
@@ -1,3 +1,4 @@
+#define __STRICT_ANSI__ /* avoid conflicting utoa */
 #include <ruby.h>
 #include <ruby/encoding.h>

Here's the RVM command I used:

$ rvm install 2.1.4 --patch cygwin.patch

That fixed the problem and allowed it to compile.  Yay!  One small note that I had to much with the patch file for a while to get the source file name correct because it has to work for where rvm runs the patch command from.  good luck!

**Comment by dayongky** [comment]
Thanks @thomasmacneil. Your patch work for me.

I also change cygwin requirements (.rvm/scripts/functions/requirements/cygwin) from mingw64-i686-gcc mingw64-x86_64-gcc to mingw64-i686-gcc-core mingw64-x86_64-gcc-core. Or it could be install first with package manager without changing cygwin file. Good luck.

**Comment by havenwood** [comment]
Closing as resolved upstream with the patch included in the release of Ruby 2.1.7 and 2.2.3.
