### ISSUE TITLE
Ruby on Rail Insatallation In Ubntu os 

### ISSUE THREAD

**Issue by abhibond007** [rvm/rvm#3450]
Installing required packages: gawk, libreadline6-dev, libyaml-dev, sqlite3, libgdbm-dev, libncurses5-dev, libffi-dev....
Error running 'requirements_debian_libs_install gawk libreadline6-dev libyaml-dev sqlite3 libgdbm-dev libncurses5-dev libffi-dev',
showing last 15 lines of /home/abhishek/.rvm/log/1434952080/package_install_gawk_libreadline6-dev_libyaml-dev_sqlite3_libgdbm-dev_libncurses5-dev_libffi-dev.log
+ sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install gawk libreadline6-dev libyaml-dev sqlite3 libgdbm-dev libncurses5-dev libffi-dev'\'': ' apt-get --no-install-recommends --yes install gawk libreadline6-dev libyaml-dev sqlite3 libgdbm-dev libncurses5-dev libffi-dev
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sqlite3 : Depends: libsqlite3-0 (= 3.7.9-2ubuntu1) but 3.7.9-2ubuntu1.1 is to be installed
E: Unable to correct problems, you have held broken packages.
+ return 100
+ return 100
Requirements installation failed with status: 100.

**Comment by abhibond007** [comment]
Whan i am going to install.

After :- source ~/.rvm/scripts/rvm

rvm requirements

after entering the password I am getting above mentioned error . 
Please help??

**Comment by havenwood** [comment]
Sorry for the very long delay before a reply.

You had an issue with held, broken packages that needed to be resolved before RVM could install dependencies via the package manager. If you're still having package manager trouble we'd be happy to help in the [#rvm IRC channel](http://webchat.freenode.net/?channels=rvm). Closing since this appears to be a broken package interfering with RVM installing packages rather than an issue with RVM itself.
