### ISSUE TITLE
rvm use jruby 9.0.0.0 installs 9.0.0.0.pre1 rather than fails or installs 9.0.0.0

### ISSUE THREAD

**Issue by applecrusher** [rvm/rvm#3475]
rvm install jruby-9.0.0.0
Searching for binary rubies, this might take some time.
Found remote file /home/ubuntu/.rvm/archives/jruby-bin-9.0.0.0.pre1.tar.gz
Checking requirements for ubuntu.
Requirements installation successful.
jruby-9.0.0.0.pre1 - #configure
jruby-9.0.0.0.pre1 - #download
jruby-9.0.0.0.pre1 - #validate archive
jruby-9.0.0.0.pre1 - #extract

I know it takes a couple of days to update but still the default for jruby 9.0.0.0 should not be .pre.

**Comment by applecrusher** [comment]
This is now fixed

**Comment by rogierslag** [comment]
In which release is this fixed located? I'm still encountering the old "pre1" version

**Comment by thehappycoder** [comment]
Same here:
$ rvm get stable
...

$ rvm install jruby-9.0.0.0
Already installed jruby-9.0.0.0.pre1.
To reinstall use:

    rvm reinstall jruby-9.0.0.0.pre1

**Comment by havenwood** [comment]
This is fixed on master and will be on stable in the forthcoming release. An `rvm get master` is the best option for the moment.

**Comment by headius** [comment]
What needs to happen to get this released?

**Comment by Sdogruyol** [comment]
@headius +1

**Comment by jodosha** [comment]
Please release :+1:

**Comment by keithrbennett** [comment]
rvm developers, thank you for your time, energy, and skill in providing for us this great tool, I've been a loyal user for several years now.  Is there any way you could release this fix?  It's now 5 months after this issue was reported, and although it's fixed on head, there are many installations beyond our control on which we rely that do not use head.  (See Travis CI issue at https://github.com/travis-ci/travis-ci/issues/4720.)

**Comment by rogierslag** [comment]
Any chance on this being released any time soon?
