### ISSUE TITLE
Jruby git clone with depth 1 option

### ISSUE THREAD

**Issue by lucianosousa** [rvm/rvm#3545]
I'm waiting for a long here to install JRuby and looks like a git clone in the full repo at
`
git@github.com:jruby/jruby.git
`
So, my suggestion is instead of that:
`
git clone git@github.com:jruby/jruby.git --depth 1
`
Will be really faster.

**Comment by sikachu** [comment]
This is currently not possible since we currently share a logic for `HEAD` version and install a specific tag/branch. You can't switch to a branch if you do a shallow clone:

```
$ git clone git@github.com:jruby/jruby.git --depth 1 
Cloning into 'jruby'...
remote: Counting objects: 13023, done.
remote: Compressing objects: 100% (10896/10896), done.
remote: Total 13023 (delta 2272), reused 7008 (delta 1335), pack-reused 0
Receiving objects: 100% (13023/13023), 9.95 MiB | 3.77 MiB/s, done.
Resolving deltas: 100% (2272/2272), done.
Checking connectivity... done.
Checking out files: 100% (12195/12195), done.
$ cd jruby 
$ git checkout 1.7.22
error: pathspec '1.7.22' did not match any file(s) known to git.
```

However, Git also recently announced a feature where you can clone a specific branch/tag/ref and it works with a `--depth=1` flag. That might be a good combination.

With that, I think I'm going to close this issue as wontfix, but I'll welcome a PR that introduce that `--depth=1` along with `--branch` option for cloning. Note that we will need to add a check for a specific version of Git as well.
