### ISSUE TITLE
Keyserver timeout

### ISSUE THREAD

**Issue by dksharp** [rvm/rvm#3665]
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 not working. Everytime its giving timeout.

**Comment by rys** [comment]
Is this still happening for you? Unfortunately it's not something we can fix, because it's your network that is stopping the connection to the keyserver. However, you can download the signing key from rvm.io and import into GPG that way, manually:

`curl -sSL https://rvm.io/mpapis.asc | gpg --import -`

Run that command and then the installation should proceed OK.
