### ISSUE TITLE
Error while trying to install JRUBY 9.1.6.0 

### ISSUE THREAD

**Issue by sam2000** [rvm/rvm#3818]
Hi,
I am getting the following error when tying to install Jruby 9.1.6.0 please could you help me do this?

```
$ rvm install jruby-9.1.6.0
Unknown ruby string (do not know how to handle): jruby-9.1.6.0
```

**Comment by raelgc** [comment]
Hi @sam2000.

Can you, please, fill the standard form info below?

_When filling an issue please make sure to follow instructions described in https://github.com/rvm/rvm#reporting-issues_

## Description

_Describe in short words the nature of your problem_


## Steps to reproduce

_List all your specific environment settings, actions taken and commands run required to replicate the problem_

 1.
 2.
 3.

## Expected behavior



## Actual behavior

_Please include [gist](https://gist.github.com) with the output of the command you have run_

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

_When above output does not seem to include meaningful error message you might want to additionally attached output of the same commands run with --debug switch_ 

* Debug mode:
** [command](https://gist.github.com/...)
** [config.log](https://gist.github.com/...) - only for issues with `install`
** [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

_Paste below the output of_

```
rvm info 
```

**Comment by sam2000** [comment]
Thanks raelgc,
Just following the first step of reading instructions at https://github.com/rvm/rvm#reporting-issues actually solved my issue. I didn't update my rvm. My bad. 
Thanks very much for your help
