### ISSUE TITLE
Detect `noexec` mount mode for partition hosting RVM home

### ISSUE THREAD

**Issue by thbar** [rvm/rvm#3832]
## Description

Installing in user mode leads to a broken install with message "permission denied" on almost all commands.

## Steps to reproduce

1. I'm installing using a dedicated user (and as a single-user install), with:
   `\curl -sSL https://get.rvm.io | bash -s -- --autolibs=read-fail`.
2. Then I'm disconnecting & reconnecting.

## Expected behavior

`rvm help` should show the help.

## Actual behavior

`rvm help` gives: `-bash: /home/myuser/.rvm/scripts/help: Permission denied`.

The same error occurs with most command (e.g. `rvm list`). `rvm version` works, though.

I noticed that most scripts under `/home/myuser/.rvm/scripts` do not have the execution bit set (unlike on another deployment via Vagrant).

## Environment info

Ubuntu Xenial (but I've also seen another deployment where this issue doesn't occur).

```
rvm info
-bash: /home/myuser/.rvm/scripts/info: Permission denied
```

**Comment by thbar** [comment]
Adding extra information:

```
$ type rvm | head -1
rvm is a function
$ rvm debug
-bash: /home/myuser/.rvm/scripts/info: Permission denied
```

**Comment by thbar** [comment]
Diving a bit further, indeed I think [chmod_if_needed](https://github.com/rvm/rvm/blob/master/scripts/functions/installer#L498) should be called on those files. I need to have a closer look at whether or not it's actually doing anything (it shows up in the installer trace).

**Comment by raelgc** [comment]
Hi @thbar and thanks for reporting this issue.

Can you, please, try our [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by thbar** [comment]
Hi @raelgc - thanks for chiming in! I saw the Ubuntu package but initially wanted to avoid mixed-mode installs in favor of per-user installations.

I'm investigating with my client IT support, one hypothesis would be that of restrictions caused by an antivirus.

I'll update the ticket and will switch the dedicated package if we cannot figure this out, thanks!

**Comment by raelgc** [comment]
Thanks for the feedback @thbar! :)

**Comment by thbar** [comment]
We got feedback from my client provider, stating that (translated) `/home` was mounted as `noexec` by default on their servers. This could definitely be the explanation.

I'll try again later today (switching clients).

I suppose this could be detected at RVM installation time (eg by running some sort of command without side-effect), yet I'm not sure how complicated it would be (but that would certainly be helpful!).

**Comment by raelgc** [comment]
@thbar Just one note about the Ubuntu install: the mixed mode will install rubies globally, but the gems will be per user (anyway, if `/home` is missing `noexec`, probably it'll be an issue anyway).

Please, if the new configuration get working for you later today, remember to Close this issue.

**Comment by thbar** [comment]
@raelgc once I had `noexec` on `/home`, the deploy went just fine. I can close this for now. Thanks!

**Comment by pkuczynski** [comment]
We can definitely fairly easily check (at least on Linux/BSD) if RVM destination folder is not on the partition mounted with `noexec` mode.

* check which partition: 
```
partition=`df -P file/goes/here | tail -1 | cut -d' ' -f 1`
```
* check mount mode:
```
mount_noexec_mode=`mount | grep -q "$partition.*noexec.*"`
```

So once @thbar confirms that this was the issue, I can add this check during installation.

**Comment by pkuczynski** [comment]
@thbar I am not sure if I understand your last comment. Did you mean that once you **removed** `noexec` from `/home` the installation went smoothly?

**Comment by thbar** [comment]
@pkuczynski sorry, I definitely wrote it backwards I think!

Here is the translation of my client IT support:

> `/home` is by default mounted as `noexec` on the servers that we install. 
> It has been remounted as `exec`.

Once they did that I was able to install RVM properly.

**Comment by pkuczynski** [comment]
Got it. I will implement `noexec` recognition on RVM side and display an error message accordingly. Thank you for working on that with us! :)

**Comment by havenwood** [comment]
Reopening because this fix was temporarily reverted in 556c42a since it was causing people to be unable to install or update.

**Comment by gnosek** [comment]
This is yet another example of rvm being too smart for its own good.

A simple "mount /tmp noexec" setup causes it to complain about /home/wherever/.rvm being mounted noexec, when it so obviously isn't:

```
root@chaos:~# mount --bind /tmp /tmp
root@chaos:~# mount /tmp -o remount,noexec
root@chaos:~# mount | grep by-uuid
/dev/disk/by-uuid/92f235ab-7ded-4be0-833b-257f2210f5d2 on / type ext4 (rw,noatime,errors=remount-ro,data=ordered)
/dev/disk/by-uuid/92f235ab-7ded-4be0-833b-257f2210f5d2 on /tmp type ext4 (rw,noexec,noatime,errors=remount-ro,data=ordered)
```

And no, further complicating the logic (e.g. parsing mount results in a smarter way) is not a solution (will you parse SELinux policies as well?). Let the installer just do its job by installing rvm and _maybe_ run some checks at the end (e.g. if ran interactively or without some --skip-checks or whatever, just let me skip them).

I wish rvm had a `--jfdi` option that just installed rvm without wishing me a nice day while also making me spend the rest of it looking for workarounds for another misfeature like this.

**Comment by pkuczynski** [comment]
Grzegorz, the only reason we included this check was because someone had opposite problem. Was trying to install RVM on the noexec partition and it was failing when trying to run some commands. You can look up the issue number in the CHANGELOG.

I would appreciate your constructive feedback or PR fixing the issue. 

I am also open to hear what are the other cases when RVM is trying to be too smart?

**Comment by gnosek** [comment]
If you're looking to solve problem X (cannot execute scripts from $HOME/.rvm) then check for X (create a file, chmod +x and execute it -- even an empty file will do) not for Y ($HOME mounted noexec), which is neither necessary nor sufficient to cause X.

Not being able to run a script will break things. Having `mount` print a line containing noexec in a particular place *will not*.

`<flashback>`
Ages ago I had to work around rvm "helpfully" checking for disk space (`df` was not available for some reason or another). That check was also wrong on several levels:
* I can't do this thing to make your life easier? Screw you, no rvm for you, I'll throw an error.
* it did not take into account quotas and other ways that make `df` irrelevant when deciding "will rvm fit?"

Trying to `sudo apt-get install` whatever when a package happens to be missing. Not every machine is a developer's laptop, not every account has sudo privileges and not every install has a human nearby to type in the password. This one at least can be disabled.

GPG signing the releases. Now, I appreciate the idea but now every single random user on my machines has to have your GPG key, which I have to autodetect and install if missing. Why isn't _this_ automated while `sudo apt-get install` is?

Constantly fighting to keep my private repo with prebuilt rubies/gemsets so installing Rails doesn't take half an eternity. By this point all that's left is a comment saying `# upstream seems hell-bent on breaking this`, so sorry, no specifics.

Also, I cannot point to a specific cause (my memory of that event has thankfully faded away and apparently I only committed the working version with `rvm-exec`) but I remember tearing half my hair out while trying to run something using an rvm gemset non interactively (without shell functions etc.).
`</flashback>`

So, back to the noexec thing. From my PoV, this whole thing should be replaced with something to the effect of:

```
echo '#!/bin/sh' > $HOME/.rvm/bin/test-exec
chmod +x $HOME/.rvm/bin/test-exec
$HOME/.rvm/bin/test-exec || {
    echo "Cannot execute $HOME/.rvm/bin/test-exec -- is the partition with $HOME/.rvm mounted with -o noexec?"
    exit 1
}
```

Of course it's just a sketch. When you know things won't work anyway, go wild with trying to detect the reason (it sure may be helpful to somebody), just don't kill the install because you _think_ it _might_ fail later on.

Alternatively, make these checks optional. Warn, if you feel like it, but don't exit with an error.
