### ISSUE TITLE
Tons of warnings when trying to use rvm and it doesn't load in shell

### ISSUE THREAD

**Issue by JohnMerlino2** [rvm/rvm#3833]
The other day I reported an issue on Ubuntu with rvm. Now I have a new issue occuring on mac osx el capiton. Using --default worked one time. Then in the future, I open the terminal, and rvm is not loaded properly. Here is an example:

$ rvm --default use 2.3@demo_web_service

Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/rvm/rvm/issues/3212

Hint: To fix PATH errors try using 'rvmsudo' instead of 'sudo', see:
    https://stackoverflow.com/questions/27784961/received-warning-message-path-set-to-rvm-after-updating-ruby-version-using-rvm/28080063#28080063

Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.0'.

RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.

/Users/inciron/.rvm/bin/rvm: line 66: shell_session_update: command not found

**Comment by mojason-81** [comment]
I'm having similar issues it seems.  However, rvm *appears* to be working.  I just keep getting the following warning when switching to a different ruby version.  Seems to only happen the *first* time I switch using `rvm use xxx` though.  Very strange.  Seems very similar to issue https://github.com/rvm/rvm/issues/3212.  Also, it seems running `rvm use xxx` (where xxx is a version number) changes my `$PATH`.  Example:

```bash
jason@wild-dog  ~
 $ echo $PATH
/home/jason/.local/share/umake/bin:/home/jason/.rvm/rubies/ruby-2.3.0/bin:/home/jason/.rvm/bin:/usr/local/heroku/bin:/home/jason/.rvm/gems/ruby-2.3.0/bin:/home/jason/.rvm/gems/ruby-2.3.0@global/bin:/home/jason/.rvm/rubies/ruby-2.3.0/bin:/home/jason/.local/share/umake/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin:/home/jason/.rvm/bin
jason@wild-dog  ~
 $ rvm use 2.2.4
Warning! PATH is not properly set up, '/home/jason/.rvm/gems/ruby-2.3.0/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.0'.
Using /home/jason/.rvm/gems/ruby-2.2.4
jason@wild-dog  ~
 $ echo $PATH
/home/jason/.rvm/gems/ruby-2.2.4/bin:/home/jason/.rvm/gems/ruby-2.2.4@global/bin:/home/jason/.rvm/rubies/ruby-2.2.4/bin:/home/jason/.rvm/bin:/home/jason/.local/share/umake/bin:/usr/local/heroku/bin:/home/jason/.local/share/umake/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
jason@wild-dog  ~
 $ rvm use 2.3.0
Using /home/jason/.rvm/gems/ruby-2.3.0
```

Some snippits from my `~/.bashrc`:
```bash
 1 [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

...
...

143 ### Added by the Heroku Toolbelt                    
144 export PATH="/usr/local/heroku/bin:$PATH"           
145                                                     
146 # Add RVM to PATH for scripting                     
147 export PATH="$HOME/.rvm/bin:$PATH"                  
148 export PATH="$HOME/.rvm/rubies/ruby-2.3.0/bin:$PATH"
```
Line 1 above, I moved out of my `~/.bash_profile` and into my `~/.bashrc` and ist seems to have gotten rid of the error/warning about GEM_PATH not being specified (or something similar).

I'm on Ubuntu 16.04 using Terminator as my terminal emulator.  I followed a suggestion from issue 3212 and checked "Run command as a login shell" in terminator's preferences.  That seemed to allow rvm to actually switch between versions, but this problem is still left over.  Seems like this issue, or issues *very* similar to this, has been around for quite some time.

**Comment by mpapis** [comment]
@mojason-81 your setup is incorrect, the sourcing line should be last thing in loading environment, not first one. You should not set the `PATH` to RVM Ruby manually it's done automatically for default ruby when RVM is sourced.

@JohnMerlino2 you got few problems:

1. Multiple problems but most important one is - you do not read the messages, they are pretty self explanatory, please follow each instruction in what you posted:

> Then in the future, I open the terminal, and rvm is not loaded properly. Here is an example:
> 
>     $ rvm --default use 2.3@demo_web_service
> 
> Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
#3212
> 
> Hint: To fix PATH errors try using 'rvmsudo' instead of 'sudo', see:
https://stackoverflow.com/questions/27784961/received-warning-message-path-set-to-rvm-after-updating-ruby-version-using-rvm/28080063#28080063
> 
> Warning! PATH is not properly set up, $GEM_HOME is not set,
usually this is caused by shell initialization files - check them for 'PATH=...' entries,
it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
to fix temporarily in this shell session run: 'rvm use ruby-2.3.0'.
> 
> RVM is not a function, selecting rubies with 'rvm use ...' will not work.
> 
> You need to change your terminal emulator preferences to allow login shell.
> Sometimes it is required to use /bin/bash --login as the command.
> Please visit https://rvm.io/integration/gnome-terminal/ for an example.

2. The next one might be because of some configuration mismatch, current version of RVM does check if the `shell_session_update` exist before adding an exit trap for it, why would fail is a mystery, do you use ZSH or share environment files with OSX machine?

> /Users/inciron/.rvm/bin/rvm: line 66: shell_session_update: command not found

**Comment by mojason-81** [comment]
@mpapis Thanks for the response.  I followed your advice, but I was still getting the same warning.  My .bashrc now looks more like:

```bash
...
...
# Add RVM to PATH for scripting
export PATH="$HOME/.rvm/bin:$PATH"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
# EOF
```

However, opening a new terminal I was still getting:

```bash
jason@wild-dog  ~
 $ rvm list
Warning! PATH is not properly set up, '/home/jason/.rvm/gems/ruby-2.3.0/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.0'.

rvm rubies

   ruby-2.2.4 [ x86_64 ]
=* ruby-2.3.0 [ x86_64 ]
   ruby-2.3.3 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

Following the directions in the warning, and running `rvm use 2.3.0` removed the warning but it was only a temporary fix.  I was going back to getting the warning when opening a new terminal.  Finally, I took the other tid-bit of advice in the warning and ran `rvm get stable --auto-dotfiles`.  Opening a new terminal and running `rvm list` no longer produces a warning.  I've ran that `... get stable...` command before and it didn't seem to make any difference, so my best guess is that I needed to fix my .bashrc per your recommendation AND run the `get stable.... ` command.  Hopefully this helps someone else that comes across this.
