### ISSUE TITLE
cant install gem bundler

### ISSUE THREAD

**Issue by Sinzole** [rvm/rvm#4436]
![gem](https://user-images.githubusercontent.com/41004651/43324113-0391df76-91bc-11e8-8b79-209b18f2cf33.JPG)

its unable to download data from http://ruby.org/
gem version 2.5.2
bundler version 1.15.3
 i do not know whats the problem please help, somebody.

**Comment by BrianHawley** [comment]
@Sinzole based on the screenshot, I'd have to ask a couple questions:
- What version of Ruby do you have installed?
- How did you install Ruby on Windows?

It's just that rvm doesn't work on Windows outside of the WSL or cygwin shells, and your screenshot shows what looks like a normal Windows command line, so whatever version of the gem command you're using here either wasn't installed by rvm or may not be expected to work in the normal Windows command line.

**Comment by havenwood** [comment]
Closing, since, as @BrianHawley mentions, this doesn't seem to be RVM related.

@Sinzole Here's [a guide for resolving RubyGems SSL errors](https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors) like yours. You also might consider switching to the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10), where you'd have bash and could use RVM.
