### ISSUE TITLE
truffleruby gem update problems

### ISSUE THREAD

**Issue by jzakiya** [rvm/rvm#4929]
rvm 1.29.10, truffleruby 20.0.0; Linux Kernel 5.5.17; Distro PCLinuxOS KDE5

Truffleruby 20.0.0 cannot update all the gems I've installed for other versions (CRuby, JRuby).

I posted an issue to Truffleruby here:  https://github.com/oracle/truffleruby/issues/2009

The reply stated I was missing build tools, e.g. gcc, but I have gcc 9.3.0 on my system.

Also, Truffleruby announced all gem tests now pass:

https://github.com/rubygems/rubygems/pull/2797#issuecomment-626150446

On my system, its been a long standing problem with Truffleruby to update certain gems, like ``BigDecimal`` in particular.

**Comment by pkuczynski** [comment]
FYI @eregon

**Comment by eregon** [comment]
Let's keep the discussion on https://github.com/oracle/truffleruby/issues/2009
I closed that issue because I thought you simply didn't install the basic build tools.

All RubyGems tests pass, it doesn't mean all gems compile/can be installed (although many can).
`bigdecimal` should install fine on `truffleruby-head`, see https://github.com/oracle/truffleruby/issues/1975

**Comment by eregon** [comment]
FWIW here is the dependencies RVM installs on PCLinuxOS:
https://github.com/rvm/rvm/blob/31ea9fb5d139ad5b7555337b80f31d2764bfc368/scripts/functions/requirements/pclinuxos#L77-L78

TruffleRuby was never tested on PCLinuxOS, so this was just a guess, maybe they need to be adapted.
