### ISSUE TITLE
Try travis.com

### ISSUE THREAD

**Issue by eregon** [rvm/rvm#5038]
It seems the CI currently uses travis-ci.org, e.g., https://travis-ci.org/github/rbenv/ruby-build/builds/755249540

As they say:
> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

Maybe migrating to travis-ci.com would make it a bit faster? Right now it's horribly long to wait for.
Probably migrating to another CI is a better long-term solution.

**Comment by pkuczynski** [comment]
I think we should rather migrate to GitHub Actions. @pedrofurtado would you maybe like to give it a try? I also agreed with @mpapis that we could inline `rvm-test` into the `rvm` repo, as it's pretty annoying to keep it in a separate one...

**Comment by pedrofurtado** [comment]
@pkuczynski I never used Github Actions, but I am compromised to study it and to plan how to implement it in RVM 🤝 📚

**Comment by pedrofurtado** [comment]
@pkuczynski @mpapis I think our migration to Github actions can be more easy if we eliminate some existing errors present in current builds. Can you help me to fix those, because currently I don't know how to deal with it 👍 

An example of build is the last commit in repo: 
Commit: https://github.com/rvm/rvm/commit/a7cc2f56c8d710c249f2f7a24cdb8e114bb4e366
Build in Travis: https://travis-ci.org/github/rvm/rvm/builds/754678004

**Comment by pedrofurtado** [comment]
Is better we finish this PR with CircleCI (https://github.com/rvm/rvm/pull/4758) or discard it and get started with Github Actions?

**Comment by eregon** [comment]
TravisCI.org no longer runs since June 15 so this is an urgent issue now:
https://travis-ci.org/github/rvm/rvm/builds

**Comment by eregon** [comment]
I'd suggest trying travis-ci.com (should be fairly straightforward, unclear how long free credits last though), and finish the work on #5040. Better smaller CI than no CI, so actually IMHO we could merge #5040 as soon as it runs the main things.
