### ISSUE TITLE
gpgkeys: HTTP fetch error 6: Could not resolve host: pool.sks-keyservers.net

### ISSUE THREAD

**Issue by issuesreporting** [rvm/rvm#5096]
When following your official installation guide  (https://rvm.io/rvm/install)

 gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

fails.

**Comment by dgm** [comment]
This site is no longer available, see website:
http://sks-keyservers.net/
Update 2021-06-21: Due to even more GDPR takedown requests, the DNS records for the pool will no longer be provided at all.

**Comment by Ajmal** [comment]
gpg --keyserver keyserver.ubuntu.com --recv-key 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

I'm using this one

**Comment by jesperronn** [comment]
The workaround by Ajmal works for me (but only on my docker images, not on MacOS)

Would be great to have a workaround that works for  both unix and mac, so that the documentation could be updated.

See also https://github.com/SKS-Keyserver/sks-keyserver/issues/81 with info that old keyservers are no longer maintained

**Comment by issuesreporting** [comment]
Yes, I know that URL is outdated. When documentation is updated this issue cases to occur as a consequence.

**Comment by dgm** [comment]
The instruction on the website are still broken - How is anyone even able to install RVM right now?

**Comment by x-yuri** [comment]
From what I can see [the recommended][a] and [the default keyserver][b] these days is `keys.openpgp.org`. This works for me:

```
$ gpg --keyserver keys.openpgp.org --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
```

Alternatively, you can use `keyserver.ubuntu.com`:

```
$ gpg --keyserver keys.openpgp.org --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
```

Apparently, `409B6B1796C275462A1703113804BB82D39DC0E3` can't be imported from `keys.openpgp.org`:

```
$ gpg --keyserver keys.openpgp.org --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: key 3804BB82D39DC0E3: no user ID
gpg: Total number processed: 1
```

Also, make sure you have `ca-certificates` installed, otherwise:

```
$ gpg --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: keyserver receive failed: General error
```

And I don't think this can be in any way OS-specific.

[a]: https://unix.stackexchange.com/questions/656205/sks-keyservers-gone-what-to-use-instead/656210#656210
[b]: https://lists.gnupg.org/pipermail/gnupg-users/2021-June/065261.html

**Comment by dgm** [comment]
> And by the way the documentation provides different commands on different pages:

Yes, one references the bad server, but without it the defaults still don't  work;  The docs need to point to the new servers that actually work.   As it is, It's impossible to install rvm using the instructions on the main rvm web page.      I would think this would be a high priority to fix!

**Comment by x-yuri** [comment]
`keys.openpgp.org` is a bad server because both keys are needed? Maybe it's not about a server, but about [the way the keys were published there][a]? Or `keys.openpgp.org` has stricter standards?

Also, with the command on the main page at least one key gets installed. Not sure if that's enough. With the command on the Installing RVM page, it fails unconditionally, since the domain name pool.sks-keyservers.net no longer exists.

[a]: https://github.com/rvm/rvm/issues/5121

**Comment by Ruin0x11** [comment]
Documentation is still outdated, it wasn't clear to me that the URL on the webpage was no longer valid. On the other hand I could use `hkp://pgp.mit.edu` without issue.

**Comment by ShockwaveNN** [comment]
Any news? I don't think documentation fix is such a hard issue?

**Comment by stuartweir** [comment]
Also curious about if there's a fix or news on this.

**Comment by wtmitchell3** [comment]
When I tried the later command, \curl -sSL https://get.rvm.io | sudo bash -s stable, without first downloading the keys, the error message gave advice that worked for me:

GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.12.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    sudo gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -
    command curl -sSL https://rvm.io/pkuczynski.asc | sudo gpg2 --import -

Running the separate "command curl" commands downloaded keys that worked for me.

**Comment by jwestonmoss** [comment]
This worked for me.

`gpg --keyserver keys.openpgp.org --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

**Comment by partriv** [comment]
> This worked for me ( more alternative key servers are mentioned at https://rvm.io/rvm/security ).
> 
> gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

this is the only one which worked for me. https://rvm.io still needs to be updated!

**Comment by sherlcok314159** [comment]
The most convenient method is to download them and import them manually on your machine. For instance, just download one key from `https://rvm.io/mpapis.asc` and upload it to your machine. Then you just need to import it by gpg2.
```bash
sudo gpg2 --import /path/to/key
```
And the second key is from `https://rvm.io/pkuczynski.asc`.

**Comment by collotebik** [comment]
this worked for me: 

sudo apt-get install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
gpg --keyserver keyserver.ubuntu.com --recv-key 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
rvm install 3.2.2
rvm use 3.2.2 --default
ruby -v
