### ISSUE TITLE
Error running '__rvm_make -j8',

### ISSUE THREAD

**Issue by 295060456** [rvm/rvm#5202]
My system is MacOS Monterey 
<img width="589" alt="image" src="https://user-images.githubusercontent.com/13795605/163871030-afd59a51-37f7-4b98-844d-fd1fda42766e.png">

when I run :
\curl -sSL https://get.rvm.io | bash -s stable --ruby

generated an err. follows

<img width="960" alt="image" src="https://user-images.githubusercontent.com/13795605/163870794-2841b26d-85a3-4014-b329-fff90cfdb0f8.png">

**Comment by cymok** [comment]
i got the same error when i run `rvm install 2.6` on termux
```
Error running '__rvm_make -j8'
```

and cat make.log
```
1 error generated.
make[2]: *** [Makefile:313: ossl.o] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/.rvm/src/ruby-2.6.10/ext/openssl'
make[1]: *** [exts.mk:243: ext/openssl/all] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/.rvm/src/ruby-2.6.10'
make: *** [uncommon.mk:286: build-ext] Error 2
++ return 2
```

**Comment by marekpetak** [comment]
Same here. using WSL on Windows 10. jruby installed & works fine, trying to install  ruby-2.7.5 I get this error.

**Comment by rakshasaini** [comment]
I am also facing the same issue in Ubuntu 22

**Comment by fcarrega** [comment]
> I have tried different _openssl_ via `rvm pkg install`, but this made no difference at all.

Did you pass the OpenSSL path when installing Ruby ? Something like that : `rvm install ruby-2.7.6 --with-openssl-dir=$HOME/.rvm/usr` ?

**Comment by marekpetak** [comment]
> > I have tried different _openssl_ via `rvm pkg install`, but this made no difference at all.
> 
> Did you pass the OpenSSL path when installing Ruby ? Something like that : `rvm install ruby-2.7.6 --with-openssl-dir=$HOME/.rvm/usr` ?

Yes. But still same problem. I have moved back to 20.04 for now

**Comment by taimourxkcd** [comment]
why is this issue still open. should have been resolved. every time i want to setup a project i get this error. where are all the developers and maintainers. why is there so much delay. should be closed with a right solution. there is no motivation in ruby community.

**Comment by monfresh** [comment]
@taimourxkcd I understand your frustration. The problem is that this is not necessarily a bug with rvm. There are many factors that can cause Ruby installation to fail, such as:

- The Xcode/command line tools version
- The macOS version
- The Mac chip (Intel or Apple Silicon)
- Whether or not you have prerequisite tools installed
- Which version manager you're using
- Which Ruby version you're trying to install
- Which Ruby configuration settings you (or the version manager) are using
- What's in your shell startup file
- `brew doctor` detecting issues with your dev setup

Also, open source maintainers don't owe anything to anyone. They're not getting paid. If there's a bug with rvm, people are free and encouraged to submit pull requests.

If you don't know how to fix this, here's what I would recommend:

- Try a different Ruby installation tool, such as rbenv, asdf, ruby-install
- Start over from scratch by uninstalling Homebrew and everything related to Ruby, and then reinstall everything
- Fix any issues `brew doctor` reports
- Back up your shell startup file, then empty it to make sure there's nothing in it that could affect Ruby installation, then reinstall rvm

If you don't feel like spending time doing all of that, and you want to use a maintained product that is updated regularly, you can buy my [Ruby on Mac](https://www.rubyonmac.dev/) product that is guaranteed to fix your Ruby installation issues in 15 minutes or less. I'm happy to answer any questions about it.

**Comment by danfodorean** [comment]
Make sure you have openssl@1.1 installed and then run:
`CFLAGS=-DUSE_FFI_CLOSURE_ALLOC rvm install ruby-3.0.0 --with-openssl-dir=$(brew --prefix openssl@1.1)`

Apparently openssl3 deprecated some stuff that rvm is using.

**Comment by monfresh** [comment]
I do not recommend using `CFLAGS=-DUSE_FFI_CLOSURE_ALLOC`. That is an unnecessary hack. If you have a proper Ruby development setup, you should never need that flag, at least on a Mac. In my 13 years of working with Ruby, I have never had to set that flag. 

Also, it's highly recommended to use the latest patch version (the 3rd digit) for any given Ruby version. So, instead of installing Ruby 3.0.0, you should use 3.0.6. This is a common point of confusion and is an important concept to understand. I wrote a detailed post about it: https://www.rubyonmac.dev/how-to-upgrade-the-ruby-version-in-your-project

Finally, the reason why Ruby 3.0 requires OpenSSL 1.1 is because OpenSSL 3 only works with Ruby versions 3.1 and higher. It has nothing to do with OpenSSL deprecating stuff that RVM is using.
