### ISSUE TITLE
Error running '__rvm_make -j16',

### ISSUE THREAD

**Issue by tejindergahir19** [rvm/rvm#5404]
rvm install ruby-3.1.0 -C --with-openssl-dir=/usr/local/bin/openssl
ruby-3.1.0 - #removing src/ruby-3.1.0 - please wait
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/tejindersingh/.rvm/rubies/ruby-3.1.0, this may take a while depending on your cpu(s)...
ruby-3.1.0 - #downloading ruby-3.1.0, this may take a while depending on your connection...
ruby-3.1.0 - #extracting ruby-3.1.0 to /Users/tejindersingh/.rvm/src/ruby-3.1.0 - please wait
ruby-3.1.0 - #configuring - please wait
ruby-3.1.0 - #post-configuration - please wait
ruby-3.1.0 - #compiling - please wait
Error running '__rvm_make -j16',
please read /Users/tejindersingh/.rvm/log/1698845705_ruby-3.1.0/make.log

There has been an error while running make. Halting the installation.

**Comment by davidkrider** [comment]
Good grief. I was getting a malloc crash in the console, and figured something had changed in my system, and my Ruby needed to be recompiled. I updated Xcode, then blew 3.2.2 away. Then I discovered it wouldn't recompile because of the still-ongoing Homebrew SSL version nonsense, and remembered that I had installed this version because it was pre-compiled with SSL 3. Now it seems that all the precompiled versions were deleted from RVM's folder structure in February of 2023, and I was stuck.

So I went through the entire rigamarole of installed `rbenv` and then finding it had the SAME PROBLEM. Then I discovered this: https://stackoverflow.com/questions/77653717/how-to-solve-double-free-for-ptr-0x7f7c33808200-in-ruby-on-rails, which fixed the console crash problem. But then I was still stuck with rbenv, and I don't want to switch everything over on all the machines.

So I kept searching, and finally found this note, which worked the first time. I've deleted rbenv, and everything seems to be working. I can compile Rubies with `rvm` using this compile flag trick, and I can connect to my production database with the console by using the Homebrew SSL trick above. Ruby is built with SSL 1, and -- apparently -- the `pg` gem is using the "system" Homebrew SSL 3 to connect to the database in the console.

I'll be glad when everything is finally on SSL 3, and our build environments start working flawlessly again. Of course, then it will just be something else. ;-)

**Comment by Kamal2301** [comment]
> This was also helpful (recent Ruby 2.5.7): [#5285 (comment)](https://github.com/rvm/rvm/issues/5285#issuecomment-1635879540)
> 
> ```
> xcode-select --install
> brew install openssl@1.1
> rvm install 3.2.2 --with-openssl-dir=$(brew --prefix openssl@1.1)
> rvm install 2.7.7 --with-openssl-dir=$(brew --prefix openssl@1.1)
> ```
> 
> These both worked ok for me on a Intel Mac with Sonoma You can use `--trace` to see the full log or switch to the `~/.rvm/logs` folder to see the logs.

Thank You

**Comment by aemooooon** [comment]
worked for me, thanks

**Comment by derickgross** [comment]
I saw a similar error message, and resolved it by specifying the architecture for an M1 Mac: `arch -arm64 rvm install 3.2.2`

**Comment by raj-yash-17** [comment]
Any resourse for ubuntu 22.04 facing the same problem ?

**Comment by LE-HU** [comment]
the only version I've managed it to work:
`PKG_CONFIG_PATH=$(brew --prefix openssl@1.1)/lib/pkgconfig rvm install 3.0.1`
note for newer versions of ruby you'd need `openssl@3`

**Comment by houhongxu** [comment]
> the only version I've managed it to work: `PKG_CONFIG_PATH=$(brew --prefix openssl@1.1)/lib/pkgconfig rvm install 3.0.1` note for newer versions of ruby you'd need `openssl@3`
thank you 🥰

**Comment by EliasTouil** [comment]
> This was also helpful (recent Ruby 2.5.7): [#5285 (comment)](https://github.com/rvm/rvm/issues/5285#issuecomment-1635879540)
> 
> ```
> xcode-select --install
> brew install openssl@1.1
> rvm install 3.2.2 --with-openssl-dir=$(brew --prefix openssl@1.1)
> rvm install 2.7.7 --with-openssl-dir=$(brew --prefix openssl@1.1)
> ```
> 
> These both worked ok for me on a Intel Mac with Sonoma You can use `--trace` to see the full log or switch to the `~/.rvm/logs` folder to see the logs.

Worked with m1 Sonoma, thanks!

**Comment by pkuczynski** [comment]
This should not be required anymore if you run `rvm get master`

**Comment by EliasTouil** [comment]
> This should not be required anymore if you run `rvm get master`

@pkuczynski Thank you Piotr I can confirm it doesn't work after a clean install of rvm ```\curl -sSL https://get.rvm.io | bash -s stable```, but it does work if I run ```rvm get master``` then ```rvm install 3.2.5```.

**Comment by blackm4c** [comment]
@pkuczynski Thank you
it works
```
curl -sSL https://get.rvm.io | bash -s stable
rvm get master
rvm install ruby
```

**Comment by ArvindSenDecathlon** [comment]
> This was also helpful (recent Ruby 2.5.7): [#5285 (comment)](https://github.com/rvm/rvm/issues/5285#issuecomment-1635879540)
> 
> ```
> xcode-select --install
> brew install openssl@1.1
> rvm install 3.2.2 --with-openssl-dir=$(brew --prefix openssl@1.1)
> rvm install 2.7.7 --with-openssl-dir=$(brew --prefix openssl@1.1)
> ```
> 
> These both worked ok for me on a Intel Mac with Sonoma You can use `--trace` to see the full log or switch to the `~/.rvm/logs` folder to see the logs.

It works me too, thank you buddy!
